export type CommandCategory = "config" | "diagnostic" | "info" | "system";
export type GuardLevel = "none" | "confirm" | "hard";

export interface ControllerCommand {
  id: string;
  label: string;
  command: string;
  category: CommandCategory;
  description: string;
  reboot_required: boolean;
  guard: GuardLevel;
  guard_message?: string;
  destructive?: boolean;
}

export const COMMANDS: ControllerCommand[] = [
  // Config — top level
  {
    id: "setup",
    label: "setup",
    command: "setup",
    category: "config",
    description: "Full first-time setup: runs setup-station, setup-system, and setup-network in sequence.",
    reboot_required: true,
    guard: "none",
  },
  {
    id: "setup-station",
    label: "setup-station",
    command: "setup-station",
    category: "config",
    description: "Station and site configuration: customer name, location, install date. Non-destructive.",
    reboot_required: true,
    guard: "none",
  },
  {
    id: "setup-system",
    label: "setup-system",
    command: "setup-system",
    category: "config",
    description: "Hydraulic hardware configuration: HHC type, zones, foam, drain. DESTRUCTIVE — does not preserve existing settings.",
    reboot_required: true,
    guard: "confirm",
    guard_message: "setup-system is destructive and will erase existing hydraulic configuration. Continue?",
    destructive: true,
  },
  {
    id: "setup-network",
    label: "setup-network",
    command: "setup-network",
    category: "config",
    description: "Network configuration: Ethernet, Wi-Fi, Cellular, Satellite, preferred network.",
    reboot_required: true,
    guard: "none",
  },
  {
    id: "setup-ethernet",
    label: "setup-ethernet",
    command: "setup-ethernet",
    category: "config",
    description: "Configure wired Ethernet. No reboot required unless primary network changes.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "setup-wifi",
    label: "setup-wifi",
    command: "setup-wifi",
    category: "config",
    description: "Configure Wi-Fi. Scans and presents available networks. No reboot required unless primary network changes.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "setup-cellular",
    label: "setup-cellular",
    command: "setup-cellular",
    category: "config",
    description: "Configure LTE-M cellular. No reboot required unless primary network changes.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "setup-satellite",
    label: "setup-satellite",
    command: "setup-satellite",
    category: "config",
    description: "Configure Iridium satellite. Reboot required. Run satellite-check after.",
    reboot_required: true,
    guard: "none",
  },
  {
    id: "setup-preferred-network",
    label: "setup-preferred-network",
    command: "setup-preferred-network",
    category: "config",
    description: "Set the primary network interface. Alerts fire if this interface loses connectivity.",
    reboot_required: true,
    guard: "none",
  },
  {
    id: "setup-server",
    label: "setup-server",
    command: "setup-server",
    category: "config",
    description: "Frontline cloud services configuration. Support use only — do not run unless instructed by engineering.",
    reboot_required: true,
    guard: "confirm",
    guard_message: "setup-server is for support use only. Only run if explicitly instructed by engineering. Continue?",
  },
  {
    id: "factory-reset",
    label: "factory-reset",
    command: "factory-reset",
    category: "config",
    description: "Resets ALL controller settings to factory defaults. Erases station, network, and system configuration.",
    reboot_required: false,
    guard: "hard",
    guard_message: "This will erase ALL controller configuration including station, network, and system settings. This cannot be undone.",
    destructive: true,
  },
  {
    id: "factory-reset-network",
    label: "factory-reset-network",
    command: "factory-reset-network",
    category: "config",
    description: "Resets network configuration only. Does not affect hydraulic or station settings.",
    reboot_required: false,
    guard: "confirm",
    guard_message: "This will erase all network configuration. Continue?",
    destructive: true,
  },

  // Diagnostic
  {
    id: "wifi-check",
    label: "wifi-check",
    command: "wifi-check",
    category: "diagnostic",
    description: "Test and confirm Wi-Fi connectivity.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cellular-check",
    label: "cellular-check",
    command: "cellular-check",
    category: "diagnostic",
    description: "Test cellular modem operation and signal level.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "ethernet-check",
    label: "ethernet-check",
    command: "ethernet-check",
    category: "diagnostic",
    description: "Test and confirm Ethernet connectivity.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "satellite-check-m",
    label: "satellite-check -m",
    command: "satellite-check -m",
    category: "diagnostic",
    description: "Monitor satellite status continuously. After 10 minutes prints visibility uptime.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "satellite-check-t",
    label: "satellite-check -t",
    command: "satellite-check -t",
    category: "diagnostic",
    description: "Run Frontline loopback satellite test. Run monitor mode first to verify visibility.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "satellite-check-r",
    label: "satellite-check -r",
    command: "satellite-check -r",
    category: "diagnostic",
    description: "Run receive mode satellite test. Requires initiating a server request when prompted.",
    reboot_required: false,
    guard: "none",
  },

  // Informational
  {
    id: "sid",
    label: "sid",
    command: "sid",
    category: "info",
    description: "Display controller serial number.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "version",
    label: "version",
    command: "version",
    category: "info",
    description: "Display controller firmware version.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "release",
    label: "release",
    command: "release",
    category: "info",
    description: "Display firmware release metadata.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-signal",
    label: "cell-signal",
    command: "cell-signal",
    category: "info",
    description: "Display cellular signal strength (0–100%).",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "wifi-signal",
    label: "wifi-signal",
    command: "wifi-signal",
    category: "info",
    description: "Display Wi-Fi signal strength.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-imei",
    label: "cell-imei",
    command: "cell-imei",
    category: "info",
    description: "Display cellular modem IMEI.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-ccid",
    label: "cell-ccid",
    command: "cell-ccid",
    category: "info",
    description: "Display SIM ICCID.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-apn",
    label: "cell-apn",
    command: "cell-apn",
    category: "info",
    description: "Display cellular APN.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-provider",
    label: "cell-provider",
    command: "cell-provider",
    category: "info",
    description: "Display cellular provider name.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "cell-status",
    label: "cell-status",
    command: "cell-status",
    category: "info",
    description: "Display cellular registration status.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "sat-imei",
    label: "sat-imei",
    command: "sat-imei",
    category: "info",
    description: "Display satellite modem IMEI.",
    reboot_required: false,
    guard: "none",
  },
  {
    id: "help",
    label: "help",
    command: "help",
    category: "info",
    description: "Display controller command help.",
    reboot_required: false,
    guard: "none",
  },

  // System
  {
    id: "reboot",
    label: "reboot",
    command: "reboot",
    category: "system",
    description: "Restart the controller. Current SSH session will drop.",
    reboot_required: false,
    guard: "confirm",
    guard_message: "Reboot the controller? The current session will disconnect.",
  },
  {
    id: "exit",
    label: "exit",
    command: "exit",
    category: "system",
    description: "Exit the controller shell session.",
    reboot_required: false,
    guard: "none",
  },
];

export const FAVORITE_COMMAND_IDS = [
  "setup",
  "setup-network",
  "wifi-check",
  "cellular-check",
  "ethernet-check",
  "satellite-check-m",
  "sid",
  "version",
  "cell-signal",
  "reboot",
];
