export type Outcome = "complete" | "escalated" | "followup";

export interface ReportAction {
  id: string;
  text: string;
  dismissed: boolean;
  autoGenerated?: boolean;
}

export interface ReportRecommendedAction {
  id: string;
  interface: "Ethernet" | "Wi-Fi" | "Cellular" | "Satellite" | "Custom";
  text: string;
  detail: string;
  dismissed: boolean;
  checked: boolean;
  custom: boolean;
}

export interface NetworkStatusRow {
  interface: "Ethernet" | "Wi-Fi" | "Cellular" | "Satellite";
  status: "green" | "orange" | "red" | "unknown";
  summary: string;
}

export interface SessionReport {
  sid: string;
  version: string;
  ip: string;
  date: string;
  generated: boolean;
  actions: ReportAction[];
  networkRows: NetworkStatusRow[];
  networkNotes: Record<string, string>;
  recommendedActions: ReportRecommendedAction[];
  notes: string;
  outcome: Outcome;
}

export const emptyReport = (): SessionReport => ({
  sid: "",
  version: "",
  ip: "",
  date: new Date().toISOString().slice(0, 10),
  generated: false,
  actions: [],
  networkRows: [],
  networkNotes: { Ethernet: "", "Wi-Fi": "", Cellular: "", Satellite: "" },
  recommendedActions: [],
  notes: "",
  outcome: "complete",
});
