export type Outcome = "complete" | "escalated" | "followup";

export interface ReportAction {
  id: string;
  /** Stable identity for auto-generated actions so dismissal survives re-polls. */
  key?: string;
  text: string;
  dismissed: boolean;
  autoGenerated?: boolean;
}

export interface ReportRecommendedAction {
  id: string;
  interface: "Ethernet" | "Wi-Fi" | "Cellular" | "Satellite" | "Pressure" | "Custom";
  text: string;
  detail: string;
  dismissed: boolean;
  checked: boolean;
  custom: boolean;
}

export interface NetworkStatusRow {
  interface: "Ethernet" | "Wi-Fi" | "Cellular" | "Satellite";
  status: "green" | "orange" | "red" | "unknown";
  summary: string;
}

export interface PressureStatusRow {
  label: "System Pressure";
  status: "green" | "orange" | "red" | "unknown";
  summary: string;
}

export interface NetworkOverride {
  status?: "green" | "orange" | "red" | "unknown";
  summary?: string;
}

export interface SessionReport {
  sid: string;
  version: string;
  ip: string;
  date: string;
  generated: boolean;
  actions: ReportAction[];
  networkRows: NetworkStatusRow[];
  pressureRows: PressureStatusRow[];
  networkNotes: Record<string, string>;
  /** User-edited overrides for network status rows — suppresses auto-population for edited fields. */
  networkOverrides: Record<string, NetworkOverride>;
  recommendedActions: ReportRecommendedAction[];
  notes: string;
  outcome: Outcome;
}

export const emptyReport = (): SessionReport => ({
  sid: "",
  version: "",
  ip: "",
  date: new Date().toISOString().slice(0, 10),
  generated: false,
  actions: [],
  networkRows: [],
  pressureRows: [],
  networkNotes: { Ethernet: "", "Wi-Fi": "", Cellular: "", Satellite: "" },
  networkOverrides: {},
  recommendedActions: [],
  notes: "",
  outcome: "complete",
});
